version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  prometheus:
    image: prom/prometheus:v2.36.0
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
