{
 "title": "proxy-go",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total count of responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "proxy_go_requests_total" }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxy_go_http_status_count{code=~\"2..|3..|4..|5..\"}"
    }
   ]
  },
  {
   "title": "Average response time over the last 5 minutes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(proxy_go_response_time_seconds_sum[5m])) / sum(rate(proxy_go_response_time_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Average throughput in KB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(proxy_go_throughput_bytes_sum[5m])) / sum(rate(proxy_go_throughput_bytes_count[5m])) / 1024\n"
    }
   ]
  }
 ]
}